### ISSUE TITLE
Alternative link Request 

### ISSUE THREAD

**Issue by Kalyan8121** [ThilakReddyy/JNTUHRESULTS-WEB#3]
Bro can you send me an alternative link 
For All JNTUH Results..

**Comment by ThilakReddyy** [comment]
Hello,
The Jntuh results Server is slow and our website completes depends on the
jntuh results site. May be students services(od) and jntuh results server
are running on same server. Try the same again at night or after 28/11/2022.


Thank you,
Thilak Reddy

**Comment by Kalyan8121** [comment]
Ok. ThankYou
